name: Backup SQLite DB to Git Repo

on:
  schedule:
    - cron: "30 16 * * *"   # daily 22:00 IST (10 PM)
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Download DB from Render
        env:
          BACKUP_URL: ${{ secrets.BACKUP_URL }}
          BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
        run: |
          mkdir backup-repo
          cd backup-repo
          # Download the live database
          curl -fSL -H "x-backup-token: $BACKUP_TOKEN" "$BACKUP_URL" -o restaurant_pos.db
          # Create timestamped compressed backup
          timestamp=$(date -u +%Y%m%dT%H%M%SZ)
          gzip -c restaurant_pos.db > restaurant_pos-${timestamp}.db.gz
          # Copy as latest.db.gz
          cp restaurant_pos-${timestamp}.db.gz latest.db.gz

      - name: Push Backup to Repo
        env:
          GIT_BACKUP_REPO: ${{ secrets.GIT_BACKUP_REPO }}
          GIT_BACKUP_TOKEN: ${{ secrets.GIT_BACKUP_TOKEN }}
        run: |
          cd backup-repo
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${GIT_BACKUP_TOKEN}@${GIT_BACKUP_REPO#https://}
          git fetch origin main || true
          git checkout -b main || git checkout main
          git add .
          git commit -m "Backup on $(date -u +%Y-%m-%dT%H:%M:%SZ)" || echo "No changes to commit"
          git push origin main --force
